{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-06-21T10:39:57.477807Z",
     "iopub.status.busy": "2025-06-21T10:39:57.476041Z",
     "iopub.status.idle": "2025-06-21T10:39:57.516967Z",
     "shell.execute_reply": "2025-06-21T10:39:57.515254Z",
     "shell.execute_reply.started": "2025-06-21T10:39:57.477751Z"
    },
    "id": "mwS2uPLzrp8l",
    "tags": []
   },
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append('/home/jupyter/datasphere/project/parser_stat')\n",
    "sys.path.append('/home/jupyter/.local/lib/python3.11/site-packages')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-06-21T09:21:42.824905Z",
     "iopub.status.busy": "2025-06-21T09:21:42.823834Z",
     "iopub.status.idle": "2025-06-21T09:24:07.690475Z",
     "shell.execute_reply": "2025-06-21T09:24:07.689463Z",
     "shell.execute_reply.started": "2025-06-21T09:21:42.824863Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: deeppavlov==1.6.0 in /home/jupyter/.local/lib/python3.11/site-packages (1.6.0)\n",
      "Requirement already satisfied: fastapi<=0.89.1,>=0.47.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (0.89.1)\n",
      "Requirement already satisfied: filelock<3.10.0,>=3.0.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (3.9.1)\n",
      "Requirement already satisfied: nltk<3.10.0,>=3.2.4 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (3.9.1)\n",
      "Requirement already satisfied: numpy<1.24 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (1.23.5)\n",
      "Requirement already satisfied: pandas<1.6.0,>=1.0.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (1.5.3)\n",
      "Requirement already satisfied: prometheus-client<=1.16.0,>=0.13.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (0.22.1)\n",
      "Requirement already satisfied: pydantic<2 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (1.10.22)\n",
      "Requirement already satisfied: pybind11==2.10.3 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (2.10.3)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.19.0 in /kernel/fallback/lib/python3.11/site-packages (from deeppavlov==1.6.0) (2.31.0)\n",
      "Requirement already satisfied: tqdm<4.65.0,>=4.42.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (4.64.1)\n",
      "Requirement already satisfied: uvicorn<0.19.0,>=0.13.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (0.18.3)\n",
      "Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (from deeppavlov==1.6.0) (0.45.1)\n",
      "Requirement already satisfied: scikit-learn==1.4.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (1.4.0)\n",
      "Requirement already satisfied: scipy==1.10.0 in /home/jupyter/.local/lib/python3.11/site-packages (from deeppavlov==1.6.0) (1.10.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /home/jupyter/.local/lib/python3.11/site-packages (from scikit-learn==1.4.0->deeppavlov==1.6.0) (1.5.1)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/jupyter/.local/lib/python3.11/site-packages (from scikit-learn==1.4.0->deeppavlov==1.6.0) (3.6.0)\n",
      "Requirement already satisfied: starlette==0.22.0 in /home/jupyter/.local/lib/python3.11/site-packages (from fastapi<=0.89.1,>=0.47.0->deeppavlov==1.6.0) (0.22.0)\n",
      "Requirement already satisfied: anyio<5,>=3.4.0 in /home/jupyter/.local/lib/python3.11/site-packages (from starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov==1.6.0) (4.9.0)\n",
      "Requirement already satisfied: idna>=2.8 in /kernel/fallback/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov==1.6.0) (3.10)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/jupyter/.local/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov==1.6.0) (1.3.1)\n",
      "Requirement already satisfied: typing_extensions>=4.5 in /home/jupyter/.local/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov==1.6.0) (4.14.0)\n",
      "Requirement already satisfied: click in /home/jupyter/.local/lib/python3.11/site-packages (from nltk<3.10.0,>=3.2.4->deeppavlov==1.6.0) (8.2.1)\n",
      "Requirement already satisfied: regex>=2021.8.3 in /home/jupyter/.local/lib/python3.11/site-packages (from nltk<3.10.0,>=3.2.4->deeppavlov==1.6.0) (2024.11.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /kernel/fallback/lib/python3.11/site-packages (from pandas<1.6.0,>=1.0.0->deeppavlov==1.6.0) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /kernel/fallback/lib/python3.11/site-packages (from pandas<1.6.0,>=1.0.0->deeppavlov==1.6.0) (2025.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /kernel/fallback/lib/python3.11/site-packages (from requests<3.0.0,>=2.19.0->deeppavlov==1.6.0) (3.4.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /kernel/fallback/lib/python3.11/site-packages (from requests<3.0.0,>=2.19.0->deeppavlov==1.6.0) (1.25.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /kernel/fallback/lib/python3.11/site-packages (from requests<3.0.0,>=2.19.0->deeppavlov==1.6.0) (2025.4.26)\n",
      "Requirement already satisfied: h11>=0.8 in /home/jupyter/.local/lib/python3.11/site-packages (from uvicorn<0.19.0,>=0.13.0->deeppavlov==1.6.0) (0.16.0)\n",
      "Requirement already satisfied: six>=1.5 in /kernel/fallback/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas<1.6.0,>=1.0.0->deeppavlov==1.6.0) (1.17.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: torch in /home/jupyter/.local/lib/python3.11/site-packages (1.13.1)\n",
      "Requirement already satisfied: typing-extensions in /home/jupyter/.local/lib/python3.11/site-packages (from torch) (4.14.0)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/jupyter/.local/lib/python3.11/site-packages (from torch) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/jupyter/.local/lib/python3.11/site-packages (from torch) (8.5.0.96)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/jupyter/.local/lib/python3.11/site-packages (from torch) (11.10.3.66)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/jupyter/.local/lib/python3.11/site-packages (from torch) (11.7.99)\n",
      "Requirement already satisfied: setuptools in /kernel/lib/python3.11/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (65.5.0)\n",
      "Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (0.45.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting transformers==4.30.2\n",
      "  Downloading transformers-4.30.2-py3-none-any.whl.metadata (113 kB)\n",
      "Requirement already satisfied: filelock in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (3.9.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (0.33.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (1.23.5)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (25.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (6.0.2)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (2024.11.6)\n",
      "Requirement already satisfied: requests in /kernel/fallback/lib/python3.11/site-packages (from transformers==4.30.2) (2.31.0)\n",
      "Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (0.13.3)\n",
      "Requirement already satisfied: safetensors>=0.3.1 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (0.5.3)\n",
      "Requirement already satisfied: tqdm>=4.27 in /home/jupyter/.local/lib/python3.11/site-packages (from transformers==4.30.2) (4.64.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter/.local/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.2) (2025.5.1)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/jupyter/.local/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.2) (4.14.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /home/jupyter/.local/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.2) (1.1.5)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /kernel/fallback/lib/python3.11/site-packages (from requests->transformers==4.30.2) (3.4.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /kernel/fallback/lib/python3.11/site-packages (from requests->transformers==4.30.2) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /kernel/fallback/lib/python3.11/site-packages (from requests->transformers==4.30.2) (1.25.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /kernel/fallback/lib/python3.11/site-packages (from requests->transformers==4.30.2) (2025.4.26)\n",
      "Downloading transformers-4.30.2-py3-none-any.whl (7.2 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.2/7.2 MB\u001b[0m \u001b[31m30.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: transformers\n",
      "  Attempting uninstall: transformers\n",
      "    Found existing installation: transformers 4.30.0\n",
      "    Uninstalling transformers-4.30.0:\n",
      "      Successfully uninstalled transformers-4.30.0\n",
      "\u001b[33m  WARNING: The script transformers-cli is installed in '/home/jupyter/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed transformers-4.30.2\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pytorch-crf in /home/jupyter/.local/lib/python3.11/site-packages (0.7.2)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: ufal.udpipe in /home/jupyter/.local/lib/python3.11/site-packages (1.3.1.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: ufal.chu-liu-edmonds in /home/jupyter/.local/lib/python3.11/site-packages (1.0.3)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "%pip install deeppavlov==1.6.0\n",
    "%pip install torch\n",
    "%pip install transformers==4.30.2\n",
    "%pip install pytorch-crf\n",
    "%pip install ufal.udpipe\n",
    "%pip install ufal.chu-liu-edmonds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "execution": {
     "iopub.execute_input": "2025-06-21T09:24:07.693429Z",
     "iopub.status.busy": "2025-06-21T09:24:07.692876Z",
     "iopub.status.idle": "2025-06-21T10:15:16.257165Z",
     "shell.execute_reply": "2025-06-21T10:15:16.255394Z",
     "shell.execute_reply.started": "2025-06-21T09:24:07.693382Z"
    },
    "id": "J9-4h7j_kwkM",
    "outputId": "b9dc3222-25a9-45f2-bbdc-5be5cb1f560e",
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "out_deeppavlov1.txt\n",
      "out_deeppavlov2.txt\n",
      "out_deeppavlov3.txt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt_tab to\n",
      "[nltk_data]     /home/jupyter/nltk_data...\n",
      "[nltk_data]   Package punkt_tab is already up-to-date!\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "  WARNING: The script transformers-cli is installed in '/home/jupyter/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "2025-06-21 09:26:39.336 INFO in 'deeppavlov.core.data.utils'['utils'] at line 97: Downloading from http://files.deeppavlov.ai/deeppavlov_data/syntax_parsing/rus_6layers.tar.gz to /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers.tar.gz\n",
      "2025-06-21 09:26:39.706 WARNING in 'deeppavlov.core.data.utils'['utils'] at line 116: Found a partial download /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers.tar.gz.part\n",
      " 71%|███████   | 1.21G/1.71G [00:00<?, ?B/s]2025-06-21 09:26:39.707 WARNING in 'deeppavlov.core.data.utils'['utils'] at line 120: Download stopped abruptly, trying to resume from 1207959552 to reach 1710734100\n",
      "100%|██████████| 1.71G/1.71G [00:08<00:00, 61.8MB/s]  \n",
      "2025-06-21 09:27:21.48 INFO in 'deeppavlov.core.data.utils'['utils'] at line 284: Extracting /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers.tar.gz archive into /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jupyter/datasphere/project/parser_stat/parser_running.py\", line 120, in <module>\n",
      "    parser = parser_class()\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/home/jupyter/datasphere/project/parser_stat/parser_running.py\", line 35, in __init__\n",
      "    self.model = build_model('syntax_ru_syntagrus_bert', install=True, download=True)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/core/commands/infer.py\", line 39, in build_model\n",
      "    deep_download(config)\n",
      "  File \"/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/download.py\", line 174, in deep_download\n",
      "    download_resource(url, dest_paths, headers)\n",
      "  File \"/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/download.py\", line 140, in download_resource\n",
      "    download_decompress(url, download_path, dest_paths, headers=headers)\n",
      "  File \"/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/core/data/utils.py\", line 288, in download_decompress\n",
      "    untar(arch_file_path, extracted_path)\n",
      "  File \"/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/core/data/utils.py\", line 212, in untar\n",
      "    tar.extractall(extract_folder)\n",
      "  File \"/usr/lib/python3.11/tarfile.py\", line 2059, in extractall\n",
      "    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),\n",
      "  File \"/usr/lib/python3.11/tarfile.py\", line 2100, in extract\n",
      "    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),\n",
      "  File \"/usr/lib/python3.11/tarfile.py\", line 2173, in _extract_member\n",
      "    self.makefile(tarinfo, targetpath)\n",
      "  File \"/usr/lib/python3.11/tarfile.py\", line 2222, in makefile\n",
      "    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)\n",
      "  File \"/usr/lib/python3.11/tarfile.py\", line 248, in copyfileobj\n",
      "    buf = src.read(bufsize)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/gzip.py\", line 301, in read\n",
      "    return self._buffer.read(size)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/_compression.py\", line 68, in readinto\n",
      "    data = self.read(len(byte_view))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/gzip.py\", line 507, in read\n",
      "    uncompress = self._decompressor.decompress(buf, size)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "zlib.error: Error -3 while decompressing data: invalid stored block lengths\n",
      "[nltk_data] Downloading package punkt_tab to\n",
      "[nltk_data]     /home/jupyter/nltk_data...\n",
      "[nltk_data]   Package punkt_tab is already up-to-date!\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "2025-06-21 09:30:42.795 INFO in 'deeppavlov.core.data.utils'['utils'] at line 97: Downloading from http://files.deeppavlov.ai/deeppavlov_data/syntax_parsing/rus_6layers.tar.gz to /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers.tar.gz\n",
      "100%|██████████| 1.71G/1.71G [00:25<00:00, 67.5MB/s]\n",
      "2025-06-21 09:33:00.56 INFO in 'deeppavlov.core.data.utils'['utils'] at line 284: Extracting /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers.tar.gz archive into /home/jupyter/.deeppavlov/models/syntax_parsing/rus_6layers\n",
      "2025-06-21 09:37:17.568 INFO in 'deeppavlov.core.data.utils'['utils'] at line 97: Downloading from http://files.deeppavlov.ai/deeppavlov_data/morpho_tagger/UD2.3/ru_syntagrus.tar.gz to /home/jupyter/.deeppavlov/downloads/UD2.3_source/ru_syntagrus.tar.gz\n",
      "100%|██████████| 16.7M/16.7M [00:00<00:00, 28.8MB/s]\n",
      "2025-06-21 09:37:18.746 INFO in 'deeppavlov.core.data.utils'['utils'] at line 284: Extracting /home/jupyter/.deeppavlov/downloads/UD2.3_source/ru_syntagrus.tar.gz archive into /home/jupyter/.deeppavlov/downloads/UD2.3_source/ru_syntagrus\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
      "  warnings.warn(\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
      "  warnings.warn(\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/transformers/modeling_utils.py:463: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  return torch.load(checkpoint_file, map_location=\"cpu\")\n",
      "Some weights of the model checkpoint at DeepPavlov/rubert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']\n",
      "- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "2025-06-21 09:39:19.435 WARNING in 'deeppavlov.core.models.torch_model'['torch_model'] at line 96: Unable to place component TorchTransformersSyntaxParser on GPU, since no CUDA GPUs are available. Using CPU.\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/core/models/torch_model.py:134: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  checkpoint = torch.load(weights_path, map_location=self.device)\n",
      "[nltk_data] Downloading package punkt_tab to\n",
      "[nltk_data]     /home/jupyter/nltk_data...\n",
      "[nltk_data]   Package punkt_tab is already up-to-date!\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "WARNING: Ignoring invalid distribution -pacy (/home/jupyter/.local/lib/python3.11/site-packages)\n",
      "\n",
      "[notice] A new release of pip is available: 24.0 -> 25.1.1\n",
      "[notice] To update, run: python3 -m pip install --upgrade pip\n",
      "2025-06-21 09:58:39.761 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/deeppavlov_data/morpho_tagger/UD2.3/ru_syntagrus.tar.gz download because of matching hashes\n",
      "2025-06-21 09:58:44.220 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/deeppavlov_data/syntax_parsing/rus_6layers.tar.gz download because of matching hashes\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
      "  warnings.warn(\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/transformers/modeling_utils.py:463: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  return torch.load(checkpoint_file, map_location=\"cpu\")\n",
      "Some weights of the model checkpoint at DeepPavlov/rubert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']\n",
      "- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n",
      "- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).\n",
      "2025-06-21 09:58:51.543 WARNING in 'deeppavlov.core.models.torch_model'['torch_model'] at line 96: Unable to place component TorchTransformersSyntaxParser on GPU, since no CUDA GPUs are available. Using CPU.\n",
      "/home/jupyter/.local/lib/python3.11/site-packages/deeppavlov/core/models/torch_model.py:134: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  checkpoint = torch.load(weights_path, map_location=self.device)\n"
     ]
    }
   ],
   "source": [
    "!for i in 1 2 3; do export FP=\"out_deeppavlov$i.txt\"; echo $FP; \\\n",
    "        python3 /home/jupyter/datasphere/project/parser_stat/parser_running.py /home/jupyter/datasphere/project/parser_stat/treebank_test_sets/treebank_data.pickle deeppavlov > $FP; done"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "DataSphere Kernel",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
